/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: EdwinRC (https://sketchfab.com/Edwin3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-nature-493b488007f14e3b98502ccc60f78582
Title: Low Poly Nature
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import islandScene from '../assets/3d/island.glb'

const Island = (props) => {
    const islandRef = useRef();
  const { nodes, materials } = useGLTF(islandScene);
  return (
  <a.group ref= {islandRef} {...props} >
  
    <mesh
      
      
      geometry={nodes.Object_2.geometry}
      material={materials.Mountain}
    />
    <mesh
      
      
      geometry={nodes.Object_3.geometry}
      material={materials.Brown}
    />
    <mesh
      
      
      geometry={nodes.Object_4.geometry}
      material={materials.Cabin}
    />
    <mesh
      
      
      geometry={nodes.Object_5.geometry}
      material={materials.Mat2}
    />
    <mesh
      
      
      geometry={nodes.Object_6.geometry}
      material={materials.Clouds}
    />
    <mesh
      
      
      geometry={nodes.Object_7.geometry}
      material={materials.Roof}
    />
    <mesh
      
      
      geometry={nodes.Object_8.geometry}
      material={materials.Dirt}
    />
    <mesh
      
      
      geometry={nodes.Object_9.geometry}
      material={materials.Material}
    />
    <mesh
      
      
      geometry={nodes.Object_10.geometry}
      material={materials.Bark}
    />
    <mesh
      
      
      geometry={nodes.Object_11.geometry}
      material={materials.Water}
    />
    <mesh
      
      
      geometry={nodes.Object_12.geometry}
      material={materials.snow}
    />
    <mesh
      
      
      geometry={nodes.Object_13.geometry}
      material={materials.Fences}
    />
    <mesh
      
      
      geometry={nodes.Object_14.geometry}
      material={materials.Fences}
    />
    <mesh
      
      
      geometry={nodes.Object_15.geometry}
      material={materials.Cave}
    />
    <mesh
      
      
      geometry={nodes.Object_16.geometry}
      material={materials.Canoe}
    />
    <mesh
      
      
      geometry={nodes.Object_17.geometry}
      material={materials.Floor}
    />
    <mesh
      
      
      geometry={nodes.Object_18.geometry}
      material={materials.Rocks}
    />
    <mesh
      
      
      geometry={nodes.Object_19.geometry}
      material={materials.Rocks}
    />
    <mesh
      
      
      geometry={nodes.Object_20.geometry}
      material={materials.Trunk}
    />
    <mesh
      
      
      geometry={nodes.Object_21.geometry}
      material={materials.Trunk}
    />
    <mesh
      
      
      geometry={nodes.Object_22.geometry}
      material={materials.Trunk}
    />
    <mesh
      
      
      geometry={nodes.Object_23.geometry}
      material={materials.Trunk}
    />
    <mesh
      
      
      geometry={nodes.Object_24.geometry}
      material={materials.Trunk}
    />
    <mesh
      
      
      geometry={nodes.Object_25.geometry}
      material={materials.Trunk}
    />
    <mesh
      
      
      geometry={nodes.Object_26.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_27.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_28.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_29.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_30.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_31.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_32.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_33.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_34.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_35.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_36.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_37.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_38.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_39.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_40.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_41.geometry}
      material={materials.Leaves}
    />
    <mesh
      
      
      geometry={nodes.Object_42.geometry}
      material={materials.Leaves}
    />
  
</a.group>
);
}

export default Island;

